apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: petstore
type: Opaque
data:
  # SECURITY WARNING: Generate a new random secret for production!
  # Use: openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
  # This is a placeholder - DO NOT use in production
  session-secret: <base64-encoded-session-secret>