apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-config
  namespace: petstore
  labels:
    app: petstore
    component: config
data:
  # Application configuration
  NODE_ENV: "production"
  PORT: "5000"
  LOG_LEVEL: "info"
  
  # Database configuration
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_TIMEOUT: "30000"
  DB_IDLE_TIMEOUT: "300000"
  
  # Session configuration
  SESSION_NAME: "petstore.sid"
  SESSION_MAX_AGE: "86400000"  # 24 hours
  SESSION_SECURE: "true"       # HTTPS required for security
  SESSION_HTTP_ONLY: "true"
  SESSION_SAME_SITE: "strict"
  
  # Security configuration
  BCRYPT_ROUNDS: "12"
  RATE_LIMIT_WINDOW: "900000"  # 15 minutes
  RATE_LIMIT_MAX: "100"       # requests per window
  
  # Feature flags
  REGISTRATION_ENABLED: "true"
  ADMIN_REGISTRATION_ENABLED: "false"
  
  # CORS configuration - UPDATE FOR PRODUCTION
  # Replace with your actual domain: https://your-domain.com
  CORS_ORIGIN: "https://localhost:3000"
  CORS_CREDENTIALS: "true"