apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: petstore
type: Opaque
data:
  # SECURITY WARNING: Use strong passwords in production!
  # Generate with: openssl rand -base64 24
  # Run utils/generate-postgres-secret.sh to update these values
  POSTGRES_PASSWORD: <base64-encoded-password>
  DATABASE_URL: <base64-encoded-connection-string>
