import { db } from "../server/db.js";
import { petCategories, pets } from "../shared/schema.js";

async function seedData() {
  try {
    console.log("Starting to seed database...");

    // Add pet categories
    const categories = await db.insert(petCategories).values([
      { name: 'Dogs', description: 'Loyal and loving canine companions' },
      { name: 'Cats', description: 'Independent and affectionate feline friends' },
      { name: 'Birds', description: 'Colorful and intelligent feathered pets' },
      { name: 'Small Animals', description: 'Rabbits, guinea pigs, and other small pets' },
      { name: 'Reptiles', description: 'Fascinating cold-blooded companions' },
      { name: 'Fish', description: 'Beautiful aquatic pets for all experience levels' }
    ]).returning();
    
    console.log('Categories created:', categories.length);

    // Add comprehensive pet collection - 35 diverse pets
    const samplePets = await db.insert(pets).values([
      // Dogs (12 pets)
      {
        name: 'Buddy',
        categoryId: categories[0].id,
        breed: 'Golden Retriever',
        age: 'Adult',
        size: 'Large',
        gender: 'Male',
        color: 'Golden',
        description: 'Buddy is a friendly and energetic Golden Retriever who loves playing fetch and swimming. He is great with kids and other dogs.',
        temperament: 'Friendly, energetic, loyal',
        adoptionFee: '250.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1552053831-71594a27632d?w=500&h=400&fit=crop'],
        tags: ['family-friendly', 'good-with-kids', 'house-trained']
      },
      {
        name: 'Charlie',
        categoryId: categories[0].id,
        breed: 'German Shepherd',
        age: 'Young',
        size: 'Large',
        gender: 'Male',
        color: 'Black and Tan',
        description: 'Charlie is an intelligent and loyal German Shepherd mix looking for an active family. He knows basic commands and loves long walks.',
        temperament: 'Intelligent, loyal, protective',
        adoptionFee: '300.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1551717743-49959800b1f6?w=500&h=400&fit=crop'],
        tags: ['needs-exercise', 'intelligent', 'guard-dog']
      },
      {
        name: 'Rocky',
        categoryId: categories[0].id,
        breed: 'Bulldog',
        age: 'Senior',
        size: 'Medium',
        gender: 'Male',
        color: 'Brindle',
        description: 'Rocky is a sweet senior bulldog who enjoys leisurely walks and lots of belly rubs. He would be perfect for a calm household.',
        temperament: 'Calm, affectionate, gentle',
        adoptionFee: '175.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=400&fit=crop'],
        tags: ['senior', 'calm', 'good-with-seniors']
      },
      {
        name: 'Bella',
        categoryId: categories[0].id,
        breed: 'Labrador Mix',
        age: 'Young',
        size: 'Medium',
        gender: 'Female',
        color: 'Chocolate',
        description: 'Bella is an energetic and playful Labrador mix who loves meeting new people and other dogs. She would thrive in an active family.',
        temperament: 'Playful, social, energetic',
        adoptionFee: '225.00',
        status: 'pending',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=500&h=400&fit=crop'],
        tags: ['energetic', 'social', 'family-friendly']
      },
      {
        name: 'Max',
        categoryId: categories[0].id,
        breed: 'Border Collie',
        age: 'Adult',
        size: 'Medium',
        gender: 'Male',
        color: 'Black and White',
        description: 'Max is a highly intelligent Border Collie who excels at agility and needs mental stimulation. Perfect for active owners who enjoy training.',
        temperament: 'Intelligent, energetic, focused',
        adoptionFee: '275.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=400&fit=crop'],
        tags: ['high-energy', 'trainable', 'needs-job']
      },
      {
        name: 'Daisy',
        categoryId: categories[0].id,
        breed: 'Beagle',
        age: 'Young',
        size: 'Medium',
        gender: 'Female',
        color: 'Tri-color',
        description: 'Daisy is a sweet Beagle with a nose for adventure. She loves exploring and would be great with children and other pets.',
        temperament: 'Curious, friendly, gentle',
        adoptionFee: '200.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=500&h=400&fit=crop'],
        tags: ['family-friendly', 'good-with-pets', 'curious']
      },
      {
        name: 'Zeus',
        categoryId: categories[0].id,
        breed: 'Great Dane',
        age: 'Adult',
        size: 'Extra Large',
        gender: 'Male',
        color: 'Fawn',
        description: 'Zeus is a gentle giant who thinks he is a lap dog. Despite his size, he is calm and loving, perfect for families with space.',
        temperament: 'Gentle, calm, affectionate',
        adoptionFee: '350.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&h=400&fit=crop'],
        tags: ['gentle-giant', 'calm', 'indoor-dog']
      },
      {
        name: 'Ruby',
        categoryId: categories[0].id,
        breed: 'Poodle',
        age: 'Young',
        size: 'Small',
        gender: 'Female',
        color: 'Apricot',
        description: 'Ruby is a smart and hypoallergenic Poodle who loves to learn tricks. She is perfect for families with allergies.',
        temperament: 'Smart, playful, hypoallergenic',
        adoptionFee: '225.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1616190260687-b6ebce95c0d3?w=500&h=400&fit=crop'],
        tags: ['hypoallergenic', 'smart', 'apartment-friendly']
      },
      {
        name: 'Cooper',
        categoryId: categories[0].id,
        breed: 'Australian Shepherd',
        age: 'Adult',
        size: 'Medium',
        gender: 'Male',
        color: 'Blue Merle',
        description: 'Cooper is an active Australian Shepherd who loves herding and outdoor activities. He needs an experienced owner with an active lifestyle.',
        temperament: 'Active, intelligent, loyal',
        adoptionFee: '300.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=500&h=400&fit=crop'],
        tags: ['herding', 'active', 'experienced-owner']
      },
      {
        name: 'Milo',
        categoryId: categories[0].id,
        breed: 'French Bulldog',
        age: 'Young',
        size: 'Small',
        gender: 'Male',
        color: 'Cream',
        description: 'Milo is a charming French Bulldog who loves being the center of attention. He is perfect for apartment living and city life.',
        temperament: 'Charming, adaptable, social',
        adoptionFee: '400.00',
        status: 'adopted',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=500&h=400&fit=crop'],
        tags: ['apartment-friendly', 'social', 'low-exercise']
      },
      {
        name: 'Luna',
        categoryId: categories[0].id,
        breed: 'Husky',
        age: 'Adult',
        size: 'Large',
        gender: 'Female',
        color: 'Gray and White',
        description: 'Luna is a beautiful Husky with striking blue eyes. She needs lots of exercise and would love a family who enjoys hiking and running.',
        temperament: 'Energetic, independent, adventurous',
        adoptionFee: '275.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=500&h=400&fit=crop'],
        tags: ['high-energy', 'hiking-buddy', 'escape-artist']
      },
      {
        name: 'Tucker',
        categoryId: categories[0].id,
        breed: 'Boxer',
        age: 'Young',
        size: 'Large',
        gender: 'Male',
        color: 'Fawn',
        description: 'Tucker is a playful Boxer who loves children and has endless energy for games. He would be perfect for an active family.',
        temperament: 'Playful, energetic, loving',
        adoptionFee: '250.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=400&fit=crop'],
        tags: ['playful', 'good-with-kids', 'energetic']
      },

      // Cats (8 pets)
      {
        name: 'Whiskers',
        categoryId: categories[1].id,
        breed: 'Domestic Shorthair',
        age: 'Young',
        size: 'Medium',
        gender: 'Female',
        color: 'Tabby',
        description: 'Whiskers is a sweet and gentle cat who loves to cuddle and purr. She enjoys sunny windowsills and interactive toys.',
        temperament: 'Gentle, affectionate, calm',
        adoptionFee: '150.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&h=400&fit=crop'],
        tags: ['indoor-cat', 'lap-cat', 'quiet']
      },
      {
        name: 'Oliver',
        categoryId: categories[1].id,
        breed: 'Maine Coon',
        age: 'Adult',
        size: 'Large',
        gender: 'Male',
        color: 'Orange',
        description: 'Oliver is a majestic Maine Coon with a fluffy coat and gentle personality. He loves being brushed and enjoys quiet companionship.',
        temperament: 'Gentle, calm, independent',
        adoptionFee: '200.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=500&h=400&fit=crop'],
        tags: ['long-haired', 'quiet', 'independent']
      },
      {
        name: 'Shadow',
        categoryId: categories[1].id,
        breed: 'Black Cat',
        age: 'Young',
        size: 'Medium',
        gender: 'Male',
        color: 'Black',
        description: 'Shadow is a sleek black cat with bright green eyes. He is playful and affectionate, breaking all superstitions about black cats.',
        temperament: 'Playful, affectionate, curious',
        adoptionFee: '125.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1561948955-570b270e7c36?w=500&h=400&fit=crop'],
        tags: ['playful', 'black-cat', 'affectionate']
      },
      {
        name: 'Princess',
        categoryId: categories[1].id,
        breed: 'Persian',
        age: 'Adult',
        size: 'Medium',
        gender: 'Female',
        color: 'White',
        description: 'Princess is a beautiful Persian cat with long, luxurious fur. She enjoys a quiet environment and regular grooming sessions.',
        temperament: 'Calm, regal, gentle',
        adoptionFee: '250.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1573824484606-433f36542e4c?w=500&h=400&fit=crop'],
        tags: ['long-haired', 'quiet', 'needs-grooming']
      },
      {
        name: 'Mittens',
        categoryId: categories[1].id,
        breed: 'Ragdoll',
        age: 'Young',
        size: 'Large',
        gender: 'Female',
        color: 'Seal Point',
        description: 'Mittens is a docile Ragdoll who loves to be held and cuddled. She goes limp when picked up, true to her breed name.',
        temperament: 'Docile, affectionate, calm',
        adoptionFee: '225.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=500&h=400&fit=crop'],
        tags: ['cuddly', 'calm', 'lap-cat']
      },
      {
        name: 'Ginger',
        categoryId: categories[1].id,
        breed: 'Orange Tabby',
        age: 'Senior',
        size: 'Medium',
        gender: 'Male',
        color: 'Orange',
        description: 'Ginger is a wise senior orange tabby who enjoys the simple pleasures of life. He would be perfect for a quiet household.',
        temperament: 'Calm, wise, gentle',
        adoptionFee: '100.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&h=400&fit=crop'],
        tags: ['senior', 'calm', 'low-maintenance']
      },
      {
        name: 'Smokey',
        categoryId: categories[1].id,
        breed: 'Russian Blue',
        age: 'Adult',
        size: 'Medium',
        gender: 'Male',
        color: 'Blue-Gray',
        description: 'Smokey is an elegant Russian Blue with a plush coat and quiet demeanor. He prefers a calm environment with routine.',
        temperament: 'Quiet, elegant, reserved',
        adoptionFee: '175.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=500&h=400&fit=crop'],
        tags: ['quiet', 'elegant', 'routine-loving']
      },
      {
        name: 'Cleo',
        categoryId: categories[1].id,
        breed: 'Siamese',
        age: 'Young',
        size: 'Medium',
        gender: 'Female',
        color: 'Seal Point',
        description: 'Cleo is a talkative Siamese who loves to have conversations with her humans. She is intelligent and social.',
        temperament: 'Vocal, intelligent, social',
        adoptionFee: '200.00',
        status: 'pending',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1571566882372-1598d88abd90?w=500&h=400&fit=crop'],
        tags: ['vocal', 'social', 'intelligent']
      },

      // Birds (5 pets)
      {
        name: 'Sunny',
        categoryId: categories[2].id,
        breed: 'Cockatiel',
        age: 'Young',
        size: 'Small',
        gender: 'Male',
        color: 'Yellow and Gray',
        description: 'Sunny is a charming cockatiel who loves to whistle and can learn simple tunes. He enjoys interacting with people and is quite social.',
        temperament: 'Social, musical, friendly',
        adoptionFee: '150.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=500&h=400&fit=crop'],
        tags: ['whistles', 'social', 'musical']
      },
      {
        name: 'Rio',
        categoryId: categories[2].id,
        breed: 'Conure',
        age: 'Adult',
        size: 'Medium',
        gender: 'Female',
        color: 'Green and Red',
        description: 'Rio is a vibrant green-cheeked conure with a playful personality. She loves toys and can learn to say a few words.',
        temperament: 'Playful, colorful, vocal',
        adoptionFee: '300.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1544863746-8ca1dda85afe?w=500&h=400&fit=crop'],
        tags: ['colorful', 'playful', 'talks']
      },
      {
        name: 'Blue',
        categoryId: categories[2].id,
        breed: 'Budgerigar',
        age: 'Young',
        size: 'Small',
        gender: 'Male',
        color: 'Blue and White',
        description: 'Blue is a beautiful budgie who loves to chirp and play with mirrors. He would do well with another budgie companion.',
        temperament: 'Cheerful, active, social',
        adoptionFee: '50.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=400&fit=crop'],
        tags: ['chirpy', 'mirror-lover', 'companion-needed']
      },
      {
        name: 'Phoenix',
        categoryId: categories[2].id,
        breed: 'Lovebird',
        age: 'Adult',
        size: 'Small',
        gender: 'Female',
        color: 'Peach and Green',
        description: 'Phoenix is a beautiful peach-faced lovebird who is very affectionate. She enjoys being out of her cage and interacting with her family.',
        temperament: 'Affectionate, interactive, social',
        adoptionFee: '125.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=400&fit=crop'],
        tags: ['affectionate', 'interactive', 'cage-free-time']
      },
      {
        name: 'Echo',
        categoryId: categories[2].id,
        breed: 'Canary',
        age: 'Young',
        size: 'Small',
        gender: 'Male',
        color: 'Yellow',
        description: 'Echo is a beautiful yellow canary with an amazing singing voice. He brings joy with his melodious songs every morning.',
        temperament: 'Musical, gentle, peaceful',
        adoptionFee: '75.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=400&fit=crop'],
        tags: ['singer', 'peaceful', 'morning-songs']
      },

      // Small Animals (6 pets)
      {
        name: 'Coco',
        categoryId: categories[3].id,
        breed: 'Holland Lop Rabbit',
        age: 'Young',
        size: 'Small',
        gender: 'Female',
        color: 'Brown and White',
        description: 'Coco is an adorable Holland Lop rabbit with floppy ears. She is litter trained and loves fresh vegetables and hay.',
        temperament: 'Gentle, quiet, sweet',
        adoptionFee: '100.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&h=400&fit=crop'],
        tags: ['litter-trained', 'quiet', 'veggie-lover']
      },
      {
        name: 'Peanut',
        categoryId: categories[3].id,
        breed: 'Guinea Pig',
        age: 'Adult',
        size: 'Small',
        gender: 'Male',
        color: 'Tri-color',
        description: 'Peanut is a social guinea pig who loves to popcorn when excited. He would do best with another guinea pig companion.',
        temperament: 'Social, active, vocal',
        adoptionFee: '50.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=500&h=400&fit=crop'],
        tags: ['social', 'popcorning', 'needs-companion']
      },
      {
        name: 'Hazel',
        categoryId: categories[3].id,
        breed: 'Netherland Dwarf Rabbit',
        age: 'Young',
        size: 'Small',
        gender: 'Female',
        color: 'Gray',
        description: 'Hazel is a tiny Netherland Dwarf rabbit with a big personality. She is curious and loves to explore safe spaces.',
        temperament: 'Curious, energetic, small',
        adoptionFee: '125.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&h=400&fit=crop'],
        tags: ['tiny', 'curious', 'explorer']
      },
      {
        name: 'Chip',
        categoryId: categories[3].id,
        breed: 'Hamster',
        age: 'Young',
        size: 'Small',
        gender: 'Male',
        color: 'Golden',
        description: 'Chip is an active golden hamster who loves running on his wheel at night. He enjoys hiding treats in his cheek pouches.',
        temperament: 'Active, nocturnal, cute',
        adoptionFee: '25.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=500&h=400&fit=crop'],
        tags: ['nocturnal', 'wheel-runner', 'cheek-pouches']
      },
      {
        name: 'Buttercup',
        categoryId: categories[3].id,
        breed: 'Guinea Pig',
        age: 'Young',
        size: 'Small',
        gender: 'Female',
        color: 'White and Brown',
        description: 'Buttercup is a gentle guinea pig who loves being petted. She would be perfect for children learning pet care responsibility.',
        temperament: 'Gentle, calm, kid-friendly',
        adoptionFee: '50.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=500&h=400&fit=crop'],
        tags: ['gentle', 'kid-friendly', 'calm']
      },
      {
        name: 'Binky',
        categoryId: categories[3].id,
        breed: 'Lionhead Rabbit',
        age: 'Adult',
        size: 'Small',
        gender: 'Male',
        color: 'White',
        description: 'Binky is a fluffy Lionhead rabbit with a distinctive mane. He loves to binky (jump for joy) when happy and enjoys being brushed.',
        temperament: 'Happy, fluffy, social',
        adoptionFee: '150.00',
        status: 'available',
        isNeutered: true,
        isVaccinated: true,
        imageUrls: ['https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=500&h=400&fit=crop'],
        tags: ['fluffy', 'binkying', 'needs-brushing']
      },

      // Reptiles (4 pets)
      {
        name: 'Scales',
        categoryId: categories[4].id,
        breed: 'Bearded Dragon',
        age: 'Adult',
        size: 'Medium',
        gender: 'Male',
        color: 'Brown and Orange',
        description: 'Scales is a calm bearded dragon who enjoys basking under his heat lamp. He is easy to handle and loves eating vegetables.',
        temperament: 'Calm, docile, easy-care',
        adoptionFee: '200.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1583585635793-0e1894c169bd?w=500&h=400&fit=crop'],
        tags: ['basking', 'easy-handle', 'veggie-eater']
      },
      {
        name: 'Emerald',
        categoryId: categories[4].id,
        breed: 'Leopard Gecko',
        age: 'Young',
        size: 'Small',
        gender: 'Female',
        color: 'Yellow with Black Spots',
        description: 'Emerald is a beautiful leopard gecko with distinctive spots. She is nocturnal and enjoys hiding in her cave during the day.',
        temperament: 'Nocturnal, gentle, easy-care',
        adoptionFee: '150.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1583585635793-0e1894c169bd?w=500&h=400&fit=crop'],
        tags: ['nocturnal', 'spotted', 'cave-dweller']
      },
      {
        name: 'Slider',
        categoryId: categories[4].id,
        breed: 'Red-Eared Slider Turtle',
        age: 'Adult',
        size: 'Medium',
        gender: 'Male',
        color: 'Green with Red Markings',
        description: 'Slider is an aquatic turtle who loves swimming and basking on his platform. He requires an aquatic setup with proper filtration.',
        temperament: 'Aquatic, calm, long-lived',
        adoptionFee: '100.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1583585635793-0e1894c169bd?w=500&h=400&fit=crop'],
        tags: ['aquatic', 'swimmer', 'long-lived']
      },
      {
        name: 'Spike',
        categoryId: categories[4].id,
        breed: 'Ball Python',
        age: 'Young',
        size: 'Medium',
        gender: 'Female',
        color: 'Brown and Black Pattern',
        description: 'Spike is a docile ball python who enjoys being handled. She is a beginner-friendly snake that requires simple care.',
        temperament: 'Docile, calm, beginner-friendly',
        adoptionFee: '175.00',
        status: 'available',
        isNeutered: false,
        isVaccinated: false,
        imageUrls: ['https://images.unsplash.com/photo-1583585635793-0e1894c169bd?w=500&h=400&fit=crop'],
        tags: ['docile', 'handleable', 'beginner-snake']
      }
    ]).returning();
    
    console.log('Pets created:', samplePets.length);
    console.log('Sample data seeded successfully!');
    console.log('Created pets:', samplePets.map(p => p.name).join(', '));
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
}

seedData();